name: Check Outdated Dependencies

on:
  schedule:
    - cron: "0 9 * * 1"

jobs:
  check_updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: | 
          npm i --global yarn npm-check-updates
          yarn
      - name: Check outdated
        run: npm-check-updates
