name: Check Outdated Dependencies

on:
  schedule:
    - cron: "0 9 * * 1"

jobs:
  check_updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Yarn
        run: npm install --global yarn
      - name: Install packages
        run: yarn
      - name: Check outdated
        run: yarn outdated
