name: Check Outdated Dependencies

on:
  workflow_dispatch

jobs:
  check_updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: | 
          npm i --global yarn npm-check-updates
          yarn
      - name: Check outdated
        run: ncu | grep -Ev 'Run ncu -u|Using yarn|Checking /'
