name: Check Outdated Dependencies

on:
  workflow_dispatch

jobs:
  check_updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: | 
          npm i --global yarn npm-check-updates
          yarn

      - name: Check outdated
        id: ncu-output-packages
        run: |
          echo 'OUTDATED_DEPENDENCIES<<EOF' >> $GITHUB_OUTPUT
          ncu | grep -Ev "Run ncu -u|Using yarn|Checking /" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Packages number
        id: ncu-output-packages-number
        run: |
          echo 'OUTDATED_DEPENDENCIES_NUMBER<<EOF' >> $GITHUB_OUTPUT
          echo "${{ steps.ncu-output-packages.outputs.OUTDATED_DEPENDENCIES }}" | wc -l | awk '{print $0-2}'>> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Conditional color
        id: ncu-output-color
        run: |
          if [[ ${{ steps.ncu-output-packages-number.outputs.OUTDATED_DEPENDENCIES_NUMBER }} -le 3 ]]; then
            echo "color=#2EB67D" >> $GITHUB_OUTPUT
          elif [[ ${{ steps.ncu-output-packages-number.outputs.OUTDATED_DEPENDENCIES_NUMBER }} -gt 3 && ${{ steps.ncu-output-packages-number.outputs.OUTDATED_DEPENDENCIES_NUMBER }} -le 10 ]]; then
            echo "color=#ECB22E" >> $GITHUB_OUTPUT
          else
            echo "color=#E01E5A" >> $GITHUB_OUTPUT
          fi
      
      - name: test
        run: |
          echo ${{ steps.ncu-output-color.outputs.color }}
      
      - name: Send notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: test-channel
          SLACK_COLOR: ${{ steps.ncu-output-color.outputs.color }}
          SLACK_MSG_AUTHOR: ' '
          SLACK_TITLE: "Repository: ${{ github.event.repository.name }}"
          SLACK_MESSAGE: "Outdated dependencies: *${{ steps.ncu-output-packages-number.outputs.OUTDATED_DEPENDENCIES_NUMBER }}* \n ${{ steps.ncu-output-packages.outputs.OUTDATED_DEPENDENCIES }} \n\n"
          MSG_MINIMAL: true
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_FOOTER: 'Powered by <https://theknotww.atlassian.net/wiki/spaces/PZ/pages/3697344976/Platform+Frontend|Platform Frontend> team with <https://www.youtube.com/watch?v=dQw4w9WgXcQ|:heart:>'
