name: Check Outdated Dependencies

on:
  workflow_dispatch

jobs:
  check_updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: | 
          npm i --global yarn npm-check-updates
          yarn
      - name: Check outdated
        id: ncu-output
        run: |
          echo 'OUTDATED_DEPENDENCIES<<EOF' >> $GITHUB_OUTPUT
          ncu | grep -Ev "Run ncu -u|Using yarn|Checking /" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - name: Send notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: test-channel
          SLACK_MSG_AUTHOR: ''
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_TITLE: "Repository: ${{github.event.repository.name}}\n"
          SLACK_MESSAGE: ${{steps.ncu-output.outputs.OUTDATED_DEPENDENCIES}}
          SLACK_USERNAME: ''
          MSG_MINIMAL: true
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_FOOTER: ''
